name: tds-did

dependencies:
  - pip=21.2.4
  - python=3.9
  - jupyter=1.0.0
  - numpy=1.21.2
  - pandas=1.4.1
  - scipy=1.7.3
  - matplotlib=3.5.0
  - seaborn=0.11.2
  - pip:
    - pycountry==22.1.10
    - pycountry-convert==0.7.2
    - openpyxl==3.0.9
    - networkx==2.6.3
